### ISSUE TITLE
Support MOI.VariablePrimalStart

### ISSUE THREAD

**Issue by hannes-uppman** [jump-dev/HiGHS.jl#126]
The second `set_start_value` in this example fails with message `ERROR: LoadError: MathOptInterface.UnsupportedAttribute{MathOptInterface.VariablePrimalStart}: Attribute MathOptInterface.VariablePrimalStart() is not supported by the model.`

```julia
using JuMP
using HiGHS

model = Model(HiGHS.Optimizer)
@variable(model, x[i=1:10], Bin)

set_start_value(x[1], 0)
optimize!(model)
set_start_value(x[1], 1)
optimize!(model)
```

I'm using HiGHS v1.1.4, JuMP v1.1.1, Julia 1.7.3.

**Comment by odow** [comment]
In fact, we don't support start values at all (the first start value is silently ignored by HiGHS). I've updated the title to reflect that.

**Comment by odow** [comment]
I talked to @blegat, and we should also look into why MOI threw an error here, instead of ignoring it.

**Comment by odow** [comment]
This requires `setHotStart` to be exposed upstream: 
https://github.com/ERGO-Code/HiGHS/blob/437c98b08710433d8a2052d341f6250b17a016c5/src/Highs.h#L933-L937
