### ISSUE TITLE
Julia version dependency for HiGHS.jl is quite restrictive

### ISSUE THREAD

**Issue by DillonJ** [jump-dev/HiGHS.jl#131]
https://github.com/jump-dev/HiGHS.jl/blob/817e7b8ad68de4cbf293fdd90088edb1be715c95/Project.toml#L13

Just wondering if the intention was to pin the version of Julia and if there is a plan to support later Julia versions?

Thanks in advance.

**Comment by odow** [comment]
This doesn't pin the version, that would be `"=1.6"`. HiGHS.jl works on any `v1.X.Y` version of Julia released after `v1.6.0`.

Read https://pkgdocs.julialang.org/v1/compatibility/

**Comment by DillonJ** [comment]
Thanks @odow, sorry about that!
