### ISSUE TITLE
Excessive printout from Highs_run()

### ISSUE THREAD

**Issue by culi122** [jump-dev/HiGHS.jl#150]
When using HiGHS.jl either directly (HiGHS_Prob) or through JuMP (JuMP_Prob), I get this extra printout when solving a problem. This happened after updating several packages to the newest version. The printout comes from Highs_run().

![image](https://user-images.githubusercontent.com/40186418/215469497-a02e57f5-72ef-4fca-88f9-180d8485e312.png)

**Comment by odow** [comment]
Do you have a reproducible example?

Can you take your JuMP `model` and call `write_to_file(model, "problem.mps")` and then upload that file?

**Comment by culi122** [comment]
Gist with model and jupyter notebook: https://gist.github.com/culi122/9b54d24fe96bf99fa22283a326176ee7

So it is the presolve that is printing results even though the model is set silent?

Isolated the problem down to one concept, could only reproduce it for this. The concept is a pumped hydro storage (PHS) plant with upper and lower reservoir (with no inflow). It can produce and pump water between the two reservoirs, using or delivering power to/from a power market (exogenous or endogenous).

**Comment by odow** [comment]
> So it is the presolve that is printing results even though the model is set silent?

It's likely just a bug in the upstream HiGHS solver that is printing despite log level being set to silent.

**Comment by odow** [comment]
Closing in favor of https://github.com/ERGO-Code/HiGHS/issues/1120.

Thanks for finding and reporting this!
