### ISSUE TITLE
Process abort while running the HiGHS solver

### ISSUE THREAD

**Issue by RandyRDavila** [jump-dev/HiGHS.jl#156]
# Description 
A account ran into an abort in production on Mar 30 while running an optimization problem on HiGHS. This happened twice:

![image](https://user-images.githubusercontent.com/33989989/231235745-9297ce9d-1771-479a-a391-73fe5caea6a3.png)

[extract-2023-04-04T19_08_47.388Z.csv(1).zip](https://github.com/jump-dev/HiGHS.jl/files/11202997/extract-2023-04-04T19_08_47.388Z.csv.1.zip)

A segmentation fault in HiGHS was also observed the next day on the same account

**Comment by odow** [comment]
Do you have a reproducible example in the form of an MPS file? @chriscoey can help you generate one internally.

**Comment by RandyRDavila** [comment]
@odow I'll look into it and get back to you.

**Comment by odow** [comment]
Any update? If not, I will close this as non-reproducible, and please re-open when you have a reproducible example.
