### ISSUE TITLE
time_limit is not respected

### ISSUE THREAD

**Issue by mzy2240** [jump-dev/HiGHS.jl#162]
Recently I found when solving MIP, using `set_time_limit_sec` to set time limit does not strictly enforce the time limit. For example, right now I am running an optimization with time_limit set as 900 seconds, it is still running now after half hour. Did not encounter the same issue in COPT or AmplNLWriter-compatible solvers.

**Comment by odow** [comment]
Duplicate of https://github.com/jump-dev/HiGHS.jl/issues/125

See
 * https://github.com/ERGO-Code/HiGHS/issues/947
 * https://github.com/ERGO-Code/HiGHS/issues/885

**Comment by odow** [comment]
> I am running an optimization with time_limit set as 900 seconds, it is still running now after half hour

Do you have the log so we can see where it got stuck?

**Comment by odow** [comment]
Do you have an MPS that replicates the issue? Otherwise I will close in favor of the upstream issues.

**Comment by odow** [comment]
Closing because this is not a bug in HiGHS.jl.
