### ISSUE TITLE
HiGHS_jll 1.5.3 not allowed?

### ISSUE THREAD

**Issue by JeffreySarnoff** [jump-dev/HiGHS.jl#165]
In a fresh directory, 
```
pkg> add HiGHS@1.5.1
...
⌅ [8fd58aa0] ↓ HiGHS_jll v1.5.3+0 ⇒ v1.5.1+0 
```
and in another directory
```
(projects) pkg> add HiGHS_jll@1.5.3
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HiGHS_jll [8fd58aa0]:
 HiGHS_jll [8fd58aa0] log:
 ├─possible versions are: 0.1.1-1.5.3 or uninstalled
 ├─restricted to versions 1.5.3 by an explicit requirement, leaving only versions: 1.5.3
 └─restricted by compatibility requirements with HiGHS [87dc4568] to versions: [0.2.0-0.2.3, 0.3.1-0.3.2, 1.1.0-1.5.1] — no versions left
```
(projects) pkg> add HiGHS_jll@1.5.3
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HiGHS_jll [8fd58aa0]:
 HiGHS_jll [8fd58aa0] log:
 ├─possible versions are: 0.1.1-1.5.3 or uninstalled
 ├─restricted to versions 1.5.3 by an explicit requirement, leaving only versions: 1.5.3
 └─restricted by compatibility requirements with HiGHS [87dc4568] to versions: [0.2.0-0.2.3, 0.3.1-0.3.2, 1.1.0-1.5.1] — no versions left
   └─HiGHS [87dc4568] log:
     ├─possible versions are: 0.1.0-1.5.1 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-1.5.1
```

**Comment by odow** [comment]
I only added here: https://github.com/jump-dev/HiGHS.jl/commit/2040c6319f1552f9ebba9d0594784963267a9d4a. I haven't tagged a release yet
