### ISSUE TITLE
time_limit behavior?

### ISSUE THREAD

**Issue by manuelma** [jump-dev/HiGHS.jl#167]
I have a `JuMP.Model` with `HiGHS.Optimizer` that I solve iteratively while modifying some constraint coefficients in between iterations. I also set the `time_limit` optimizer attribute to something like 300 seconds. I have the suspicion that the timer is not reset everytime I call `optimize!`, so after a few hundred iterations I start hitting the time limit immediately. Do you think that's possible?

**Comment by odow** [comment]
That seems like a good explanation. Unfortunately, it means that the problem is in https://github.com/ERGO-Code/HiGHS, not in HiGHS.jl. Let me take a look.

**Comment by odow** [comment]
Confirmed upstream issue: https://github.com/ERGO-Code/HiGHS/issues/1331

**Comment by odow** [comment]
Just to update this issue: I've added `Highs_zeroAllClocks` to upstream: https://github.com/ERGO-Code/HiGHS/pull/1332. So we can fix this once the next version of HiGHS is released.
