### ISSUE TITLE
MathOptInterface.TerminationStatus() unsupported for HiGHS

### ISSUE THREAD

**Issue by bhalonen** [jump-dev/HiGHS.jl#17]
```
ArgumentError: ModelLike of type HiGHS.Optimizer does not support accessing the attribute MathOptInterface.TerminationStatus()
Stacktrace:
  [1] get_fallback(::HiGHS.Optimizer, ::MathOptInterface.TerminationStatus)
    @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:292
  [2] get(::HiGHS.Optimizer, ::MathOptInterface.TerminationStatus)
  ```
  is there any plan to support this? seems fairly essential to using the solver.

**Comment by odow** [comment]
The wrapper is unfinished. There is still a lot of the interface un-implemented. 

PRs accepted. If you want to learn MOI, it is a good project to get stuck into.

**Comment by bhalonen** [comment]
got this done, there are definitely more parts to implement, just managed to get to the next error. I'll drop a PR in.

**Comment by odow** [comment]
Closing because this is done. I'm working on a re-write of the MOI wrapper.
