### ISSUE TITLE
Time limit not compliant with MOI interface

### ISSUE THREAD

**Issue by hlefebvr** [jump-dev/HiGHS.jl#190]
Hello,

The HiGHS solver currently compares the time limit with the global run time, i.e., the cumulative run time of all runs with a given HiGHS object. 

This is to be changed in version 2.0 as indicated [in this HiGHS issue](https://github.com/ERGO-Code/HiGHS/issues/1477).

In the meantime, this makes `HiGHS.jl` violating the [MOI interface specifications](https://jump.dev/JuMP.jl/stable/api/JuMP/#JuMP.set_time_limit_sec) and preventing interchangeability of solvers within the JuMP environment. 

An easy fix (until version 2.0 release) is to set the time limit to "getRunTime() + time_limit" where "time_limit" is the actual time limit, instead of "time_limit". 

Thank you.

**Comment by odow** [comment]
This is fixed with HiGHS v1.6:

https://github.com/jump-dev/HiGHS.jl/blob/fa6247b826c9a208ceeddc576d631a61e04a82e0/src/MOI_wrapper.jl#L1817-L1820

**Comment by odow** [comment]
See also https://github.com/jump-dev/HiGHS.jl/issues/125, https://github.com/jump-dev/HiGHS.jl/issues/162

**Comment by hlefebvr** [comment]
Thanks a lot!
