### ISSUE TITLE
HiGHS v1.7

### ISSUE THREAD

**Issue by odow** [jump-dev/HiGHS.jl#204]
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/8246

**Comment by kpamnany** [comment]
We're looking forward to this one @odow because it removes the `SIGINT` handler that `exit`s. So with this update, `Ctrl+C` at the Julia prompt will not force the REPL to exit as it currently does.

**Comment by mzy2240** [comment]
My benchmark is ready to test if the MIP performance improves or not
