### ISSUE TITLE
`Highs_resetGlobalScheduler` not defined 

### ISSUE THREAD

**Issue by jd-lara** [jump-dev/HiGHS.jl#209]
MWE

```Julia
using JuMP, HiGHS
model = Model(HiGHS.Optimizer)
Highs_resetGlobalScheduler(1)
set_attribute(model, MOI.NumberOfThreads(), 1)
```

**Comment by odow** [comment]
You must have an old version of HiGHS:

https://github.com/jump-dev/HiGHS.jl/blob/1d192e20410b2e71c7cf1eaab48d3e533f3f8902/src/gen/libhighs.jl#L2244-L2262

**Comment by odow** [comment]
Closing because @jd-lara is using an old version of HiGHS that doesn't include this, and the version he is using is not thread-safe.
