### ISSUE TITLE
`set_binary` notworking if `solver = ipm`

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/HiGHS.jl#241]
```julia
m = Model(optimizer_with_attributes(HiGHS.Optimizer, "solver"=>"ipm"))
@variable(m, x)
set_binary(x)
```

```
ERROR: Constraints of type MathOptInterface.VariableIndex-in-MathOptInterface.ZeroOne are not supported by the solver.

If you expected the solver to support your problem, you may have an error in your formulation. Otherwise, consider using a different solver.

The list of available solvers, along with the problem types they support, is available at https://jump.dev/JuMP.jl/stable/installation/#Supported-solvers.
```

**Comment by odow** [comment]
We should probably remove this: 
https://github.com/jump-dev/HiGHS.jl/blob/201cbed80e6b96429ed747a425f35b75bf64bd13/src/MOI_wrapper.jl#L2412-L2418

But the solution for you is to remove the ipm option.

**Comment by joaquimg** [comment]
Did you git-blame that?
it seems uncommon to have such a check.

**Comment by joaquimg** [comment]
I might also has fallen in the issue: "HiGHS is hanging on windows". I think it was solved recently

**Comment by odow** [comment]
The blame was me way back in https://github.com/jump-dev/HiGHS.jl/pull/50.

Present-self does not agree with the decision that past-self made.

> I think it was solved recently

Yip. Update to the latest HiGHS.jl@1.10 and HiGHS_jll@1.8.0
