### ISSUE TITLE
Status of IPM code?

### ISSUE THREAD

**Issue by mlubin** [jump-dev/HiGHS.jl#44]
@odow mentioned that the IPM solver is not yet enabled through the Julia interface. What's blocking it? I'm interested in running experiments with HiGHS/IPM as a baseline.

**Comment by odow** [comment]
@galabovaa had it disabled in the HiGHS_jll builds: https://github.com/JuliaPackaging/Yggdrasil/blob/463ad9cc9acb89fb1f2ebb1c9467c4080df68844/H/HiGHS/build_tarballs.jl#L33

I think there was some refactoring going on.

**Comment by mlubin** [comment]
@galabovaa @jajhall, is the IPM code ready to be used at this point?

**Comment by odow** [comment]
@galabovaa is working on a new JLL release: https://github.com/JuliaPackaging/Yggdrasil/pull/2711

**Comment by mlubin** [comment]
Oh, nice! :)
