### ISSUE TITLE
Add QP interface

### ISSUE THREAD

**Issue by odow** [jump-dev/HiGHS.jl#54]
This is currently blocked by a way to set the Q matrix through the C API without providing the full model.

Upstream issue: https://github.com/ERGO-Code/HiGHS/issues/530

**Comment by jajhall** [comment]
This is long since fixed - even in v1.1

**Comment by odow** [comment]
Yip. I have a branch working on adding support, but it isn't finished: https://github.com/jump-dev/HiGHS.jl/pull/56

**Comment by odow** [comment]
Closed by #56
