### ISSUE TITLE
Add support for indicator constraints

### ISSUE THREAD

**Issue by SupplyChef** [jump-dev/HiGHS.jl#57]
When solving a model with indicator constraints I get the below error message. It would be great to have support for indicator constraints.

MOI.VectorAffineFunction{Float64}`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}` constraints are not supported and cannot be bridged into supported constrained variables and constraints. See details below:
   [1] constrained variables in `MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}` are not supported because no added bridge supports bridging it.
     Cannot add free variables and then constrain them because:
     (2) `MOI.VectorOfVariables`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}` constraints are not supported
   [4] constrained variables in `MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}` are not supported because no added bridge supports bridging it.
     Cannot add free variables and then constrain them because:
     (9) `MOI.VectorOfVariables`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}` constraints are not supported
   [5] constrained variables in `MOI.SOS1{Float64}` are not supported because no added bridge supports bridging it.
     Cannot add free variables and then constrain them because:
     (10) `MOI.VectorOfVariables`-in-`MOI.SOS1{Float64}` constraints are not supported
   (1) `MOI.VectorAffineFunction{Float64}`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}` constraints are not supported because:
     Cannot use `MOIB.Constraint.VectorSlackBridge{Float64, MOI.VectorAffineFunction{Float64}, MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}}` because:
     [1] constrained variables in `MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}` are not supported
     Cannot use `MOIB.Constraint.IndicatorActiveOnFalseBridge{Float64, MOI.VectorAffineFunction{Float64}, MOI.EqualTo{Float64}}` because:
     (8) `MOI.VectorAffineFunction{Float64}`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}` constraints are not supported
   (2) `MOI.VectorOfVariables`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}` constraints are not supported because:
     Cannot use `MOIB.Constraint.VectorFunctionizeBridge{Float64, MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}}` because:
     (1) `MOI.VectorAffineFunction{Float64}`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ZERO, MOI.EqualTo{Float64}}` constraints are not supported
   (8) `MOI.VectorAffineFunction{Float64}`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}` constraints are not supported because:
     Cannot use `MOIB.Constraint.VectorSlackBridge{Float64, MOI.VectorAffineFunction{Float64}, MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}}` because:
     [4] constrained variables in `MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}` are not supported
     Cannot use `MOIB.Constraint.IndicatorSOS1Bridge{Float64, MOI.EqualTo{Float64}, Nothing}` because:
     (10) `MOI.VectorOfVariables`-in-`MOI.SOS1{Float64}` constraints are not supported
   (9) `MOI.VectorOfVariables`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}` constraints are not supported because:
     Cannot use `MOIB.Constraint.VectorFunctionizeBridge{Float64, MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}}` because:
     (8) `MOI.VectorAffineFunction{Float64}`-in-`MOI.IndicatorSet{MOI.ACTIVATE_ON_ONE, MOI.EqualTo{Float64}}` constraints are not supported
     Cannot use `MOIB.Constraint.IndicatorSOS1Bridge{Float64, MOI.EqualTo{Float64}, Nothing}` because:
     (10) `MOI.VectorOfVariables`-in-`MOI.SOS1{Float64}` constraints are not supported
   (10) `MOI.VectorOfVariables`-in-`MOI.SOS1{Float64}` constraints are not supported because:
     Cannot use `MOIB.Constraint.VectorFunctionizeBridge{Float64, MOI.SOS1{Float64}}` because:
     (11) `MOI.VectorAffineFunction{Float64}`-in-`MOI.SOS1{Float64}` constraints are not supported
   (11) `MOI.VectorAffineFunction{Float64}`-in-`MOI.SOS1{Float64}` constraints are not supported because:
     Cannot use `MOIB.Constraint.VectorSlackBridge{Float64, MOI.VectorAffineFunction{Float64}, MOI.SOS1{Float64}}` because:
     [5] constrained variables in `MOI.SOS1{Float64}` are not supported

**Comment by odow** [comment]
HiGHS does not support indicator constraints so we can't support this.
