### ISSUE TITLE
problem on HiGHS version

### ISSUE THREAD

**Issue by nht2018** [jump-dev/HiGHS.jl#72]
When I use the following command to install highs,
```
import Pkg
Pkg.add("HiGHS")
```
the version of HiGHS installed is  v0.2.3. How do I install the latest version of HiGHS (v1.1)?
Thanks.

**Comment by odow** [comment]
HiGHS.jl (the Julia package) is v0.2.3, but it uses HiGHS_jll (the solver) version 1.1:
https://github.com/jump-dev/HiGHS.jl/blob/567ed76f40fe4fa0e65979219367054afca6b287/Project.toml#L11
