### ISSUE TITLE
Why QP failures are allowed?

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/HiGHS.jl#99]
These are allowed to fail in many tests.
```julia
const _QP_FAILURES = [
    "test_objective_qp_ObjectiveFunction_edge_cases",
    "test_objective_qp_ObjectiveFunction_zero_ofdiag",
    "test_quadratic_duplicate_terms",
    "test_quadratic_integration",
    "test_quadratic_nonhomogeneous",
]
```
Is it a problem upstream?

**Comment by odow** [comment]
I think it's something to do with how we were setting options. If you use the defaults, everything passes:
https://github.com/jump-dev/HiGHS.jl/blob/de218441bc179f1489f470d3c3b4aa943974cc34/test/MOI_wrapper.jl#L27-L45
If you force the algorithm, there were failures:
https://github.com/jump-dev/HiGHS.jl/blob/de218441bc179f1489f470d3c3b4aa943974cc34/test/MOI_wrapper.jl#L47-L82

But there's been some fixes to the QP solver, so we should revisit the exclusions.

**Comment by odow** [comment]
See https://github.com/ERGO-Code/HiGHS/pull/970. These failures are expected.
